apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    name: db-pod
    type: voting-app
spec:
  containers:
   - name: db-pod
     image: postgres
     ports:
       - containerPort: 5432
     env:
       - name: POSTGRES_USER
         value: "postgres"
       - name: POSTGRES_PASSWORD
         value: "postgres"
           
     