apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db-service
    type : voting-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: db-pod
    type: voting-app
        
     