apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: redis-pod
    type: voting-app
spec:
  containers:
   - name: redid-pod
     image: redis
     ports:
       - containerPort: 6379

     