
apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    type : voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
     name: result-app-pod
     type: voting-app
        
      