
apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    type : voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  selector:
       name: voting-app-pod
       type: voting-app
        
      